import { StyleSheet } from 'react-native';
import vw from '../../utils/size-dynamic/';
import { themes } from '../../constants';
export default StyleSheet.create({
  container: {
    backgroundColor: themes.colors.WHITE,
    marginBottom: vw(7),
    borderRadius: vw(5),
    ...themes.SHADOW,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: vw(10),
    paddingVertical: vw(5),
    borderBottomWidth: 0.5,
    borderBottomColor: themes.colors.BORDER_BOTTOM_CART,
  },
  containerContext: {
    flexDirection: 'row',
    width: '100%',
    backgroundColor: themes.colors.WHITE,
    borderRadius: vw(5),
    marginBottom: vw(5),
    paddingVertical: vw(5),
    paddingHorizontal: vw(10),
  },
  imageContainer: {
    marginRight: vw(5),
    alignItems: 'center',
    justifyContent: 'center',
  },
  inforContainer: {
    flex: 2,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginLeft: vw(5),
  },
  image: {
    width: vw(60),
    height: vw(60),
  },
  text: {
    color: themes.colors.BLACK,
    fontSize: vw(12),
  },
  textPrice: {
    color: themes.colors.RED,
    fontSize: vw(13),
    fontWeight: '500',
  },
  textBold: {
    color: themes.colors.BLACK,
    fontWeight: 'bold',
    fontSize: vw(12),
  },
  textBlue: {
    fontSize: vw(12),
    color: themes.colors.BLUE,
    fontFamily: themes.fontFamily.fontFamily,
    fontWeight: '300',
  },
  lineBottom: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputContainer: {
    color: themes.colors.COLOR_INPUT_PRICE,
    padding: 0,
    textAlign: 'center',
    fontSize: vw(12),
    fontWeight: 'bold',
    flex: 1,
  },
  //modal
  buttonAcceptModal: {
    flex: 1,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  hitSlop: {
    top: 20,
    bottom: 20,
    left: 20,
    right: 20,
  },
  containerModal: {
    flex: 1,
    justifyContent: 'space-between',
  },
  dialogStyle: {
    zIndex: 100,
    borderRadius: vw(10),
    overflow: 'hidden',
    height: vw(300),
  },
  title: {
    textAlign: 'center',
    fontSize: vw(17),
    color: themes.colors.BLACK_BASIC,
    paddingTop: 15,
    fontWeight: 'bold',
  },
  line: {
    width: '100%',
    height: 1,
    backgroundColor: themes.colors.GRAY,
    opacity: 0.5,
    marginTop: 5,
  },
  item: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 15,
    paddingRight: 15,
    height: 40,
  },
  button: {
    borderWidth: 1,
    borderRadius: 5,
    borderColor: themes.colors.GRAY,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 5,
    marginRight: 5,
  },
  inputOrder: {
    borderWidth: 1,
    borderColor: themes.colors.GRAY,
    width: 60,
    borderRadius: 3,
    justifyContent: 'center',
    alignItems: 'center',
    height: 30,
    paddingTop: 0,
    paddingBottom: 0,
    textAlign: 'center',
  },
  modalContainer: {
    height: 20,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginLeft: vw(5),
    borderRadius: vw(2),
    borderWidth: 1,
    borderColor: themes.colors.MAIN_COLOR,
    paddingLeft: vw(3),
  },
  dropdownStyle: {
    width: vw(70),
    maxHeight: vw(120),
    borderRadius: 3,
    marginLeft: vw(5),
  },
  buttonTrash: {
    position: 'absolute',
    bottom: vw(7),
    right: vw(10),
  },
  iconTrash: {
    width: vw(15),
    height: vw(15),
    resizeMode: 'contain',
    tintColor: themes.colors.MAIN_COLOR,
  },
  iconOperator: {
    fontWeight: 'bold',
    fontSize: 15,
  },
  wapperInput: {
    flexDirection: 'row',
    alignItems: 'center',
    width: vw(40),
    height: vw(20),
    borderColor: themes.colors.BORDER_COLOR,
    backgroundColor: themes.colors.BACKGROUND_BOX_INPUT,
    borderWidth: 0.5,
    borderRadius: 3,
  },
  iconCarteDown: {
    width: vw(6),
    height: vw(6),
    resizeMode: 'contain',
    marginRight: vw(5),
  },
});
