# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App' do
  pod 'Firebase/Messaging','~> 5.20.1'
  pod 'Firebase/Core','~> 5.20.1'
  pod 'SwiftyJSON', '5.0'
  pod 'Charts', '3.3.0'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge', # Include this for RN >= 0.47
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket', # Needed for debugging
  'RCTAnimation', # Needed for FlatList and animations running on native UI thread
  # Add any other subspecs you want to use in your project
  'RCTImage',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'TextDetector',
  'FaceDetectorMLKit',
  'BarcodeDetectorMLKit'
  ]
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-print', :path => '../node_modules/react-native-print'

  pod 'react-native-html-to-pdf', :path => '../node_modules/react-native-html-to-pdf'

end


