import { StyleSheet } from 'react-native';
import vw from '../../utils/size-dynamic/';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E7E7E7',
  },
  title: {
    fontSize: vw(14),
    fontWeight: 'bold',
    color: '#4F4F4F',
    marginBottom: vw(10),
    fontFamily: 'Arial',
  },
  wrapInfo: {
    backgroundColor: '#ffffff',
    padding: vw(10),
    borderRadius: vw(5),
  },
  infoItem: {
    marginBottom: vw(5),
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  infoItemIcon: {
    width: vw(10),
    height: vw(10),
    resizeMode: 'contain',
    marginRight: vw(5),
    marginTop: vw(5),
  },
  infoItemWrapText: {
    flexDirection: 'row',
    flex: 2,
    paddingRight: vw(30),
    alignItems: 'flex-start',
  },
  infoItemText: {
    fontSize: vw(14),
    color: '#4F4F4F',
    fontFamily: 'Arial',
  },
  wrapProductItem: {
    borderBottomWidth: 5,
    borderBottomColor: '#e5e5e5',
  },
  wrapFooter: {
    elevation: 5,
    backgroundColor: '#ffffff',
    zIndex: 10,
  },
  footerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: vw(3),
  },
  footerItemText: {
    fontSize: vw(14),
    fontFamily: 'Arial',
    color: '#828282',
  },
  wrapBtn: {
    backgroundColor: '#61A02C',
    borderRadius: vw(5),
    paddingHorizontal: vw(10),
    paddingVertical: vw(5),
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnText: {
    fontSize: vw(15),
    fontFamily: 'Arial',
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  containerOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(0,0,0,.3)',
    zIndex: 0,
  },
  iconClose: {
    width: vw(15),
    height: vw(15),
    resizeMode: 'contain',
  },
  txtSummaryFooter: {
    flex: 1,
    textAlign: 'center',
    fontSize: vw(14),
    fontWeight: 'bold',
    fontFamily: 'Arial',
    color: '#4F4F4F',
  },
  containerError: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconCaretDown: {
    width: 6,
    height: 6,
    resizeMode: 'contain',
  },
  txtSumAmountCurrent: {
    fontSize: vw(16),
    fontFamily: 'Arial',
    color: '#4F4F4F',
    fontWeight: 'bold',
  },
  txtSum: {
    fontSize: vw(10),
    fontFamily: 'Arial',
    color: '#828282',
    marginRight: vw(3),
  },
  buttonFooterAnimation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: vw(10),
    zIndex: 10,
  },
  containerFooter: {
    zIndex: 0,
    overflow: 'hidden',
  },
  imageInvoice: {
    width: '100%',
    height: 300,
    resizeMode: 'contain',
  },
  txtImageInvoice: {
    fontWeight: 'bold',
    paddingBottom: 10,
  },
  containerListProduct: {
    backgroundColor: '#ffffff',
    paddingVertical: vw(5),
    marginBottom: vw(10),
    paddingHorizontal: vw(10),
    borderRadius: 3,
  },
  infoItemTitle: {
    fontSize: vw(16),
    color: '#333333',
    fontWeight: 'bold',
    marginBottom: vw(10),
  },
  txtCampaign: {
    color: 'black',
    fontSize: vw(12),
    fontFamily: 'Arial',
    paddingBottom: 10,
  },
  containerCampaign: {
    paddingHorizontal: vw(10),
    paddingTop: vw(5),
    paddingBottom: vw(10),
    backgroundColor: '#f2f2f2',
  },
  iconCaretDownCampaign: {
    width: vw(10),
    height: vw(6),
    resizeMode: 'contain',
    tintColor: 'white',
  },
  txtCampaignAdvNote: {
    color: 'white',
    fontSize: vw(14),
    fontFamily: 'Arial',
    marginRight: vw(3),
    fontWeight: 'bold',
  },
  buttonCampaignAdv: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: vw(8),
  },
  iconTrans: {
    width: vw(10),
    height: vw(16),
    resizeMode: 'contain',
    marginRight: vw(3),
  },
  cancelOrder: {
    color: '#ffffff',
    fontSize: vw(14),
  },
  iconBack: {
    width: vw(11),
    height: vw(20),
    resizeMode: 'contain',
    marginRight: vw(10),
  },
  txtHeaderLeft: {
    fontSize: vw(18),
    fontFamily: 'Arial',
    fontWeight: 'bold',
    color: '#ffffff',
  },
  buttonHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  txtCampaignDrugName: {
    fontSize: vw(14),
    fontWeight: 'bold',
    paddingBottom: 5,
  },
});
