# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  # release beta (staging)
  lane :beta do
    increment_build_number(xcodeproj: "App.xcodeproj", build_number: Time.now.strftime(‘%Y%m%d%H%M’)[2,11])
    sync_code_signing(type: "appstore")
    build_app(scheme: "App",
              workspace: "App.xcworkspace",
              include_bitcode: true)
    upload_to_testflight(skip_waiting_for_build_processing: true)
    slack(
      slack_url:"https://hooks.slack.com/services/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",
      message: "Medlink Pharmacy Successfully distributed a new beta build"
    )
  end

  lane :production do
    increment_build_number(xcodeproj: "App.xcodeproj", build_number: Time.now.strftime(‘%Y%m%d%H%M’)[2,11])
    sync_code_signing(type: "appstore")
    build_app(scheme: "App Release",
              workspace: "App.xcworkspace",
              include_bitcode: true)
    upload_to_testflight(skip_waiting_for_build_processing: true)
    slack(
      slack_url:"https://hooks.slack.com/services/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",
      message: "Medlink Pharmacy Successfully distributed a new beta build"
    )
  end
  # export screenshots
  lane :screenshots do
    capture_screenshots
    frame_screenshots(white: true)
    #upload_to_app_store
  end
end
