import { StyleSheet, Modal, Platform } from 'react-native';
import vw from '../../utils/size-dynamic/';
import { themes } from '../../constants/';
import { title, body } from '../../constants/themes';
export default StyleSheet.create({
  container: {
    flex: 1,
  },
  txtHeader: {
    fontSize: vw(18),
    fontFamily: themes.fontFamily.fontFamily,
    fontWeight: 'bold',
    color: themes.colors.WHITE,
  },
  iconBack: {
    width: vw(11),
    height: vw(20),
    resizeMode: 'contain',
    marginRight: vw(10),
  },
  buttonSearch: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: themes.colors.BACKGROUND_BOX_INPUT,
    borderRadius: 5,
    margin: vw(10),
    paddingHorizontal: vw(10),
    height: vw(40),
  },
  iconSearch: {
    width: vw(21),
    height: vw(21),
    resizeMode: 'contain',
  },
  textSearch: {
    color: themes.colors.PLACEHOLDER_INPUT,
    height: vw(40),
    flex: 1,
    paddingVertical: vw(10),
    fontSize: vw(14),
  },
  containerSearch: {
    backgroundColor: themes.colors.WHITE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backgroundPayment: {
    backgroundColor: themes.colors.WHITE,
    padding: vw(10),
  },
  wapperButtonCheck: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonCheck: {
    width: vw(15),
    height: vw(15),
    backgroundColor: themes.colors.WHITE,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: vw(3),
    marginRight: vw(8),
    borderColor: themes.colors.MAIN_COLOR,
    borderWidth: vw(1),
  },
  iconCheck: {
    width: vw(10),
    height: vw(10),
    resizeMode: 'contain',
  },
  txtCOD: {
    color: 'black',
    fontSize: vw(12),
  },
  wapperTitle: {
    padding: vw(10),
    height: vw(40),
    backgroundColor: themes.colors.BACKGROUND_COLOR,
  },
  txtListProduct: {
    fontSize: vw(16),
    color: themes.colors.BLACK,
    fontWeight: 'bold',
  },
  waperLayout: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: vw(10),
  },
  informationFlex: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 7,
  },
  textInput: {
    flex: 1,
    borderBottomColor: themes.colors.MAIN_COLOR,
    borderBottomWidth: vw(1),
    height: vw(40),
    paddingLeft: vw(5),
    paddingVertical: vw(5),
    fontSize: vw(14),
  },
  buttonFooter: {
    marginHorizontal: vw(10),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: themes.colors.MAIN_COLOR,
    height: vw(33),
    borderRadius: vw(5),
    width: '90%',
  },
  txtButtonAdd: {
    fontSize: vw(15),
    fontWeight: 'bold',
    color: themes.colors.WHITE,
  },
  containerFooter: {
    width: '100%',
    height: vw(50),
    backgroundColor: themes.colors.WHITE,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: vw(10),
    alignItems: 'center',
  },
  amountMoney: {
    color: themes.colors.BLACK_BASIC,
    fontWeight: 'bold',
    fontSize: vw(16),
  },
  createInvoice: {
    width: vw(125),
    height: vw(33),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: vw(5),
  },
  txtCreateInvoice: {
    color: themes.colors.WHITE,
    fontWeight: 'bold',
    fontSize: vw(15),
  },
  containerCheckbox: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: vw(10),
    backgroundColor: themes.colors.WHITE,
  },
  buttonVNPay: {
    marginTop: vw(5),
    // flex: 3,
  },
  backgroundModal: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  ModalInsideView: {
    backgroundColor: themes.colors.WHITE,
    height: '40%',
    width: '90%',
    borderRadius: vw(5),
    padding: vw(10),
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  buttonModal: {
    width: '80%',
    height: vw(40),
    backgroundColor: themes.colors.MAIN_COLOR,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: vw(5),
  },
  txtModalCancel: {
    color: themes.colors.WHITE,
    ...body,
    fontWeight: 'bold',
  },
  txtConnecting: {
    fontSize: vw(14),
    color: themes.colors.MAIN_COLOR,
    marginTop: vw(5),
    fontStyle: 'italic',
  },
  iconNoti: {
    width: vw(50),
    height: vw(50),
    resizeMode: 'contain',
  },
  wapperModalNoti: {
    alignItems: 'center',
    width: '100%',
    justifyContent: 'center',
    alignContent: 'center',
  },
  titleNoti: {
    ...title,
  },
  detailNoti: {
    textAlign: 'center',
    ...body,
    color: themes.colors.BLACK,
  },
  buttonLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  txt14: {
    fontSize: vw(14),
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputDiscountByInvoice: {
    height: vw(30),
    flex: 1,
    // backgroundColor: themes.colors.BACKGROUND_BOX_INPUT,
    padding: vw(0),
    fontSize: vw(14),
    // marginHorizontal: vw(5),
    paddingLeft: vw(5),
    borderBottomColor: themes.colors.MAIN_COLOR,
    borderBottomWidth: vw(1),
  },
  wapperQuanlityDrug: {
    alignItems: 'center',
    justifyContent: 'space-around',
    height: vw(20),
    width: vw(70),
    borderColor: themes.colors.MAIN_COLOR,
    borderWidth: vw(1),
    flexDirection: 'row',
    marginLeft: vw(5),
  },
  styleModal: {
    width: vw(150),
    maxHeight: vw(120),
    borderRadius: vw(3),
    overflow: 'hidden',
    marginRight: -vw(10),
    ...Platform.select({
      ios: {
        shadowColor: 'black',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.14,
        shadowRadius: 2,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  txtModal: {
    fontSize: vw(10),
    color: themes.colors.MAIN_COLOR,
    fontFamily: themes.fontFamily.fontFamily,
  },
  iconCaretDown: {
    width: vw(6),
    height: vw(6),
    resizeMode: 'contain',
    marginRight: vw(5),
  },
});
